<?php
/**
 * Created by PhpStorm.
 * User: João Paulo
 * Date: 09/09/2018
 * Time: 21:41
 */

namespace InovationZone\Poo\Polimorfismo;

class Tubarao extends Peixe
{
    public function alimentar()
    {
       // parent::alimentar(); // TODO: Change the autogenerated stub
        echo "come outros peixes";
    }
}