<?php
/**
 * Created by PhpStorm.
 * User: João Paulo
 * Date: 09/09/2018
 * Time: 21:41
 */

require_once 'Peixe.php';
class Tubarao extends peixe
{
    public function alimentar()
    {
       // parent::alimentar(); // TODO: Change the autogenerated stub
        echo "come outros peixes";
    }
}